const $=s=>document.querySelector(s);const intro=$('#intro'),quest=$('#quest'),reveal=$('#reveal');const startBtn=$('#startBtn'),moveBtn=$('#moveBtn'),acceptBtn=$('#acceptBtn');const token=$('#token'),tiles=$('#tiles'),msg=$('#message'),bar=$('#barFill'),toast=$('#toast');
let audioCtx, step=0; const total=10; const icons=['🍷','🎲','🃏','🍿','😂','🍫','✨','🍸','👑','🏁']; const messages=['Quest started!','Wine unlocked 🍷','Dice power unlocked 🎲','Cards unlocked 🃏','Snacks unlocked 🍿','Friendship risk +80% 😂','Chocolate bonus unlocked 🍫','Almost there ✨','Champion energy detected 👑','Finish line reached 🏁'];
function initAudio(){ if(audioCtx) return; audioCtx=new (window.AudioContext||window.webkitAudioContext)(); }
function tone(freq=440,dur=.08,type='sine',vol=.05){ if(!audioCtx)return; const o=audioCtx.createOscillator(),g=audioCtx.createGain(); o.type=type;o.frequency.value=freq;g.gain.value=vol;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.stop(audioCtx.currentTime+dur); }
function clickSound(){tone(520,.06,'square',.035);setTimeout(()=>tone(780,.06,'square',.025),55)}function winSound(){[523,659,784,1046].forEach((f,i)=>setTimeout(()=>tone(f,.14,'triangle',.055),i*120))}
function show(panel){[intro,quest,reveal].forEach(p=>p.classList.remove('active'));panel.classList.add('active');window.scrollTo(0,0)}
function showToast(t){toast.textContent=t;toast.classList.add('show');setTimeout(()=>toast.classList.remove('show'),1200)}
function buildTiles(){tiles.innerHTML='';icons.slice(0,12).forEach((ic,i)=>{const d=document.createElement('div');d.className='tile';d.textContent=ic;tiles.appendChild(d)})}
function pos(){const board=document.querySelector('.board'); const w=board.clientWidth-92,h=board.clientHeight-92; const points=[[38,38],[w*.35,38],[w*.66,38],[w,38],[w, h*.38],[w*.66,h*.38],[w*.35,h*.38],[38,h*.38],[38,h*.72],[w*.35,h*.72],[w*.66,h*.72],[w,h*.72]]; const p=points[Math.min(step,points.length-1)]; token.style.left=p[0]+'px'; token.style.top=p[1]+'px'; token.style.transform=`rotate(${step*35}deg) scale(${step===total?1.18:1})`; bar.style.width=(step/total*100)+'%'}
startBtn.addEventListener('click',()=>{initAudio();clickSound();buildTiles();show(quest);step=0;pos();showToast('Player connected ✨')});
moveBtn.addEventListener('click',()=>{initAudio();clickSound(); if(step>=total)return; step++; pos(); msg.textContent=messages[step]||'Keep going →'; if(navigator.vibrate) navigator.vibrate(25); if(step===1||step===3||step===5||step===8) showToast(messages[step]); if(step>=total){moveBtn.disabled=true;moveBtn.textContent='UNLOCKING...';winSound();confetti();setTimeout(()=>{show(reveal);confetti();},950)}});
acceptBtn.addEventListener('click',()=>{initAudio();winSound();$('#achievement').classList.add('show');confetti();showToast('Mission accepted 💜')});
function confetti(){for(let i=0;i<80;i++){const c=document.createElement('i');c.className='confetti';c.style.left=Math.random()*100+'vw';c.style.background=['#ff2bd6','#45e7ff','#ffd12e','#5cff88','#fff'][Math.floor(Math.random()*5)];c.style.animationDelay=Math.random()*.4+'s';document.body.appendChild(c);setTimeout(()=>c.remove(),2200)}}
const canvas=$('#stars'),ctx=canvas.getContext('2d');let stars=[];function resize(){canvas.width=innerWidth;canvas.height=innerHeight;stars=Array.from({length:90},()=>({x:Math.random()*canvas.width,y:Math.random()*canvas.height,r:Math.random()*1.7+.4,v:Math.random()*.45+.15}))}function draw(){ctx.clearRect(0,0,canvas.width,canvas.height);ctx.fillStyle='rgba(255,255,255,.85)';stars.forEach(s=>{ctx.beginPath();ctx.arc(s.x,s.y,s.r,0,Math.PI*2);ctx.fill();s.y+=s.v;if(s.y>canvas.height)s.y=-5});requestAnimationFrame(draw)}addEventListener('resize',resize);resize();draw();
